servers:
  hosts:
    pve:
      set_hostname: pve
      ansible_ssh_host: 192.168.4.48
      ansible_ssh_common_args: "-o ControlPath=/tmp/%r@%h:%p"
    pve-docker:
      set_hostname: pve-docker
      ansible_ssh_host: 192.168.4.68
  vars:
    ansible_connection: ssh
    ansible_ssh_private_key_file: ~/.ssh/mournfully.key
    ansible_become: true
    ansible_become_pass: "{{ become_pass }}"
    ansible_user: sysadmin
    ansible_ssh_port: 3022
