---
- name: Update pve-hypervisor sources
  hosts: all

  tasks:
    - name: Remove enterprise proxmox repos
      ansible.builtin.apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
        state: absent
        filename: pve-enterprise
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['distribution_major_version'] == "11"

    - name: Add free proxmox repos
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        state: present
        filename: pve-install-repo
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['distribution_major_version'] == "11"

    - name: Add non-free debian repos
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        filename: debian-11-nonfree
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['distribution_major_version'] == "11"
      loop:
        - deb http://deb.debian.org/debian bullseye non-free
        - deb-src http://deb.debian.org/debian bullseye non-free
        - deb http://deb.debian.org/debian-security/ bullseye-security non-free
        - deb-src http://deb.debian.org/debian-security/ bullseye-security non-free
        - deb http://deb.debian.org/debian bullseye-updates non-free
        - deb-src http://deb.debian.org/debian bullseye-updates non-free

    - name: Update packages
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
